#!/bin/tcsh
#PBS -N usgsB
#PBS -l nodes=1:bora:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe


# init conda within new shell for job
source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load openmpi/2.1.1/gcc-4.9.4
unsetenv PYTHONPATH
conda activate env

cd usgs

python dl.py SLV 2007


